"""Tests for the auth blueprint - OAuth login flow."""

import base64
import json
from datetime import datetime, timedelta, timezone
from unittest.mock import MagicMock, call, patch

import pytest


def _make_id_token(email="test@example.com", name="Test User", picture=""):
    """Build a minimal fake JWT ID token with the given claims."""
    payload = {
        "email": email,
        "name": name,
        "picture": picture,
        "exp": int((datetime.now(timezone.utc) + timedelta(hours=1)).timestamp()),
    }
    payload_b64 = base64.urlsafe_b64encode(json.dumps(payload).encode()).decode().rstrip("=")
    return f"fakeheader.{payload_b64}.fakesig"


def _mock_flow(code_verifier="test_verifier_xyz", email="test@example.com"):
    """Return a mock Flow object pre-configured with sensible defaults."""
    flow = MagicMock()
    flow.authorization_url.return_value = (
        "https://accounts.google.com/o/oauth2/auth?response_type=code",
        "test_state",
    )
    flow.code_verifier = code_verifier
    flow.credentials.id_token = _make_id_token(email=email)
    return flow


class TestLoginPage:
    def test_renders_when_unauthenticated(self, client):
        """GET /login without a session should render the login page."""
        with patch("presentation.web.blueprints.auth.get_session_datasource") as mock_ds:
            mock_ds.return_value.get_session.return_value = None
            response = client.get("/login")
        assert response.status_code == 200

    def test_redirects_when_already_authenticated(self, client):
        """GET /login with a valid session cookie should redirect away."""
        with patch("presentation.web.blueprints.auth.get_session_datasource") as mock_ds:
            mock_ds.return_value.get_session.return_value = MagicMock()
            client.set_cookie("session_token", "valid_token")
            response = client.get("/login")
        assert response.status_code == 302


class TestLoginStart:
    def test_redirects_to_google(self, client):
        """GET /login/start should redirect to Google's OAuth endpoint."""
        flow = _mock_flow()
        with patch("presentation.web.blueprints.auth.get_credentials_loader_instance") as mock_cl, \
             patch("presentation.web.blueprints.auth.Flow") as mock_flow_cls:
            mock_cl.return_value.get_credentials.return_value = {"web": {}}
            mock_flow_cls.from_client_config.return_value = flow
            response = client.get("/login/start")
        assert response.status_code == 302
        assert "accounts.google.com" in response.headers["Location"]

    def test_saves_state_and_flow_marker_to_session(self, client):
        """oauth_state and oauth_flow must be stored in the session after /login/start."""
        flow = _mock_flow()
        with patch("presentation.web.blueprints.auth.get_credentials_loader_instance") as mock_cl, \
             patch("presentation.web.blueprints.auth.Flow") as mock_flow_cls:
            mock_cl.return_value.get_credentials.return_value = {"web": {}}
            mock_flow_cls.from_client_config.return_value = flow
            client.get("/login/start")
        with client.session_transaction() as sess:
            assert sess["oauth_state"] == "test_state"
            assert sess["oauth_flow"] == "login"

    def test_saves_pkce_code_verifier_to_session(self, client):
        """The PKCE code_verifier generated by the flow must be persisted in the session
        so that login_callback can pass it to fetch_token on the new Flow instance."""
        flow = _mock_flow(code_verifier="verifier_abc123")
        with patch("presentation.web.blueprints.auth.get_credentials_loader_instance") as mock_cl, \
             patch("presentation.web.blueprints.auth.Flow") as mock_flow_cls:
            mock_cl.return_value.get_credentials.return_value = {"web": {}}
            mock_flow_cls.from_client_config.return_value = flow
            client.get("/login/start")
        with client.session_transaction() as sess:
            assert sess["oauth_code_verifier"] == "verifier_abc123"

    def test_no_code_verifier_not_saved_to_session(self, client):
        """If PKCE is disabled (code_verifier is None), key must not appear in session."""
        flow = _mock_flow(code_verifier=None)
        with patch("presentation.web.blueprints.auth.get_credentials_loader_instance") as mock_cl, \
             patch("presentation.web.blueprints.auth.Flow") as mock_flow_cls:
            mock_cl.return_value.get_credentials.return_value = {"web": {}}
            mock_flow_cls.from_client_config.return_value = flow
            client.get("/login/start")
        with client.session_transaction() as sess:
            assert "oauth_code_verifier" not in sess


class TestLoginCallback:
    def _setup_session(self, client, code_verifier="verifier_abc"):
        with client.session_transaction() as sess:
            sess["oauth_state"] = "test_state"
            sess["oauth_flow"] = "login"
            if code_verifier is not None:
                sess["oauth_code_verifier"] = code_verifier

    def _patch_callback(self, flow, allowed_emails=None, onboarding_step=0):
        """Return a context manager stack that patches all callback dependencies."""
        return (
            patch("presentation.web.blueprints.auth.get_credentials_loader_instance",
                  return_value=MagicMock(get_credentials=MagicMock(return_value={"web": {}}))),
            patch("presentation.web.blueprints.auth.Flow",
                  **{"from_client_config.return_value": flow}),
            patch("presentation.web.blueprints.auth.get_session_datasource",
                  return_value=MagicMock(create_session=MagicMock(return_value="new_token"))),
            patch("presentation.web.blueprints.auth.get_allowed_emails_list",
                  return_value=allowed_emails),
            patch("presentation.web.blueprints.auth._get_onboarding_status_for_user",
                  return_value={"step": onboarding_step}),
            patch("presentation.web.utils.get_user_settings_service"),
        )

    def test_missing_state_redirects_to_login(self, client):
        """Callback with no oauth_state in session should redirect back to /login."""
        response = client.get("/login/callback?state=test_state&code=auth_code")
        assert response.status_code == 302
        assert "/login" in response.headers["Location"]

    def test_wrong_flow_marker_redirects_to_login(self, client):
        """Callback with oauth_flow != 'login' should redirect back to /login."""
        with client.session_transaction() as sess:
            sess["oauth_state"] = "test_state"
            sess["oauth_flow"] = "gmail"
        response = client.get("/login/callback?state=test_state&code=auth_code")
        assert response.status_code == 302
        assert "/login" in response.headers["Location"]

    def test_fetch_token_receives_pkce_code_verifier(self, client):
        """fetch_token must be called with the code_verifier that was saved in the session,
        completing the PKCE handshake and preventing the 'Missing code verifier' error."""
        self._setup_session(client, code_verifier="verifier_abc123")
        flow = _mock_flow(code_verifier=None)  # new Flow instance has no verifier itself
        patches = self._patch_callback(flow)
        with patches[0], patches[1] as mock_flow_cls, patches[2], patches[3], patches[4], patches[5]:
            mock_flow_cls.from_client_config.return_value = flow
            client.get("/login/callback?state=test_state&code=auth_code")
        _, kwargs = flow.fetch_token.call_args
        assert kwargs.get("code_verifier") == "verifier_abc123"

    def test_fetch_token_receives_none_when_no_code_verifier_in_session(self, client):
        """If no code_verifier was saved (PKCE disabled), fetch_token receives None."""
        self._setup_session(client, code_verifier=None)
        flow = _mock_flow(code_verifier=None)
        patches = self._patch_callback(flow)
        with patches[0], patches[1] as mock_flow_cls, patches[2], patches[3], patches[4], patches[5]:
            mock_flow_cls.from_client_config.return_value = flow
            client.get("/login/callback?state=test_state&code=auth_code")
        _, kwargs = flow.fetch_token.call_args
        assert kwargs.get("code_verifier") is None

    def test_code_verifier_cleared_from_session_after_use(self, client):
        """oauth_code_verifier must be removed from session after the callback (no replay)."""
        self._setup_session(client, code_verifier="verifier_abc123")
        flow = _mock_flow(code_verifier=None)
        patches = self._patch_callback(flow)
        with patches[0], patches[1] as mock_flow_cls, patches[2], patches[3], patches[4], patches[5]:
            mock_flow_cls.from_client_config.return_value = flow
            client.get("/login/callback?state=test_state&code=auth_code")
        with client.session_transaction() as sess:
            assert "oauth_code_verifier" not in sess

    def test_disallowed_email_returns_403(self, client):
        """Email not in the allowed list should return 403 without creating a session."""
        self._setup_session(client, code_verifier=None)
        flow = _mock_flow(email="blocked@example.com")
        with patch("presentation.web.blueprints.auth.get_credentials_loader_instance") as mock_cl, \
             patch("presentation.web.blueprints.auth.Flow") as mock_flow_cls, \
             patch("presentation.web.blueprints.auth.get_session_datasource"), \
             patch("presentation.web.blueprints.auth.get_allowed_emails_list",
                   return_value={"allowed@example.com"}):
            mock_cl.return_value.get_credentials.return_value = {"web": {}}
            mock_flow_cls.from_client_config.return_value = flow
            response = client.get("/login/callback?state=test_state&code=auth_code")
        assert response.status_code == 403

    def test_successful_login_sets_session_cookie(self, client):
        """A successful callback should set a session_token cookie and redirect."""
        self._setup_session(client, code_verifier="verifier_abc")
        flow = _mock_flow(email="user@example.com")
        patches = self._patch_callback(flow)
        with patches[0], patches[1] as mock_flow_cls, patches[2], patches[3], patches[4], patches[5]:
            mock_flow_cls.from_client_config.return_value = flow
            response = client.get("/login/callback?state=test_state&code=auth_code")
        assert response.status_code == 302
        assert "session_token" in response.headers.get("Set-Cookie", "")


class TestLogout:
    def test_logout_clears_session_cookie(self, client):
        """GET /logout should expire the session_token cookie."""
        with patch("presentation.web.blueprints.auth.get_session_datasource") as mock_ds:
            mock_ds.return_value.delete_session.return_value = None
            client.set_cookie("session_token", "some_token")
            response = client.get("/logout")
        assert response.status_code == 302
        assert "/login" in response.headers["Location"]
